doctrine:
    dbal:
        driver: 'pdo_pgsql'
        charset: utf8
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '17'
        logging: true
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

        mappings:
            App\Entities:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entities/'
                prefix: 'App\Entities'
